Lisansüstü çalışmalarda, birçok öğrenci okullarda aldıkları desteğe kıyasla yüksek öğrenim derslerinde çok fazla destek alamadıkları için iyi notlar almakta zorluk çekiyor. Öğrenci notlarının tahmin edilmesi görevi için makine öğrenimini kullanabiliriz, böylece eğitmenler öğrencilerin notlarının düşük tahmin edildiği konulara hazırlanmalarına yardımcı olabilir. Bu makalede, Python kullanarak Makine Öğrenimi ile öğrenci notlarının tahmin edilmesi görevini adım adım anlatacağım.

Öğrenci Not Tahmini
Üniversiteler yüksek öğrenime erişim için çok prestijli yerlerdir. Ancak üniversitelerin bugün talep ettiği ücret miktarı, öğrencilere verdikleri desteğe asla eşit değildir. Bazı öğrenciler eğitmenlerden çok fazla ilgiye ihtiyaç duyarlar çünkü iyi notlar almayan öğrencilere özel ilgi gösterilmezse, bu onların duygusal durumları ve uzun vadede kariyerleri için zararlı olabilir.

Makine öğrenimi algoritmalarını kullanarak, notları düşük tahmin edilen öğrencilere yardımcı olabilmek için öğrencilerin ne kadar iyi performans göstereceklerini tahmin edebiliriz. Öğrenci Not Tahmini, makine öğrenimindeki regresyon sorununa dayanmaktadır. Aşağıdaki bölümde, Python kullanarak makine öğrenimiyle Öğrenci Not Tahmini görevini size göstereceğim.

Python Kullanarak Öğrenci Not Tahmini
Umarım artık bir öğrencinin notlarını neden tahmin etmemiz gerektiğini anlamışsınızdır. Şimdi Python kullanarak öğrenci notlarını tahmin etme görevi için makine öğrenimini nasıl kullanabileceğimizi görelim. Bu göreve gerekli Python kütüphanelerini ve veri setini içe aktararak başlayacağım:

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split


ben farklı olarak csv datayı linkten direkt almayı seçtim

In [2]:
%pip install requests

Note: you may need to restart the kernel to use updated packages.


In [3]:
import requests

# URL of the CSV file
url = "https://raw.githubusercontent.com/amankharwal/Website-data/master/student-mat.csv"

# Send a GET request to fetch the raw content
response = requests.get(url)

# Write the content to a file
with open("student-mat.csv", "wb") as file:
    file.write(response.content)

print("CSV file has been downloaded successfully.")

CSV file has been downloaded successfully.


Öğrencilerin not tahmini görevi için kullandığım veri seti, Portekiz okullarındaki öğrencilerin başarılarına dayanmaktadır. Bu veri setinde G1, ilk dönemin notlarını, G2, ikinci dönemin notlarını ve G3, final notlarını temsil eder. Şimdi verileri hazırlayalım ve öğrencilerin final notlarını nasıl tahmin edebileceğimizi görelim:

In [4]:
import pandas as pd

# URL of the CSV file
url = "https://raw.githubusercontent.com/amankharwal/Website-data/master/student-mat.csv"

# Read the CSV file directly from the URL into a DataFrame
df = pd.read_csv(url)
data = pd.read_csv("student-mat.csv")
data.head()
# Display the first few rows of the DataFrame
print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]


In [5]:
# URL of the CSV file
url = "https://raw.githubusercontent.com/amankharwal/Website-data/master/student-mat.csv"

# Load the dataset into a pandas DataFrame
data = pd.read_csv(url)

# Select the relevant features and the target
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]

# Define the target variable
predict = "G3"

# Features (X) - drop the target column 'G3'
x = np.array(data.drop([predict], axis=1))

# Target (y) - the 'G3' column
y = np.array(data[predict])

# Split the data into training and test sets (80% training, 20% testing)
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

# Check the shapes of the training and test sets
print(f"xtrain shape: {xtrain.shape}")
print(f"xtest shape: {xtest.shape}")
print(f"ytrain shape: {ytrain.shape}")
print(f"ytest shape: {ytest.shape}")

xtrain shape: (316, 5)
xtest shape: (79, 5)
ytrain shape: (316,)
ytest shape: (79,)


Yukarıdaki kodda, öncelikle öğrenci notu tahmini görevi için bir makine öğrenimi modeli eğitmek için ihtiyaç duyduğumuz gerekli sütunları seçtim. Daha sonra G3 sütununu hedef etiket olarak ilan ettim ve ardından veri setini %20 test ve %80 eğitim olarak böldüm. Şimdi öğrenci notu tahmini görevi için doğrusal regresyon modelinin nasıl eğitileceğini görelim:

In [6]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.7821754247320556


Doğrusal regresyon modeli bu görevde fena olmayan yaklaşık %84'lük bir doğruluk verdi. Şimdi öğrencilerin not tahmin modelinin yaptığı tahminlere bir bakalım:

In [7]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[12.70478596 18.6925959   3.42583945  6.01113762 18.6925959 ]
 [12.70478596 12.70478596  3.42583945  6.01113762  7.87300271]
 [ 7.10011213  7.22885591  3.42583945  8.52243043 14.95294333]
 ...
 [14.95294333  7.22885591 12.20306263  8.52243043  8.52243043]
 [ 6.26901605 13.65241561 12.20306263  6.01113762  6.01113762]
 [ 7.22885591 12.6388124  12.20306263  6.01113762 12.70478596]] [[[12 13  2  0  0]
  [19 18  2  0  2]
  [ 3  5  2  1  8]
  [ 8  8  1  3  2]
  [19 18  2  0  2]]

 [[12 13  2  0  0]
  [12 13  2  0  0]
  [ 3  5  2  1  8]
  [ 8  8  1  3  2]
  [ 9  9  2  2 11]]

 [[ 9  7  2  0 18]
  [ 8  8  2  0  0]
  [ 3  5  2  1  8]
  [ 8  9  2  0  8]
  [14 15  2  0  0]]

 ...

 [[14 15  2  0  0]
  [ 8  8  2  0  0]
  [14 12  1  0  3]
  [ 8  9  2  0  8]
  [ 8  9  2  0  8]]

 [[ 7  7  3  0  6]
  [12 14  3  0  1]
  [14 12  1  0  3]
  [ 8  8  1  3  2]
  [ 8  8  1  3  2]]

 [[ 8  8  2  0  0]
  [11 13  2  0  2]
  [14 12  1  0  3]
  [ 8  8  1  3  2]
  [12 13  2  0  0]]] [array([[13, 18,  5, 10, 18]